spring:
  application:
    name: TWITTERFAKE_DEV
  datasource:
    url: jdbc:h2:mem:twitterfake;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: exampleClientId
            client-secret: exampleClientSecret

jwt:
  secret:
    key: exampleSecretKey
  user:
    generator: exampleUserGenerator

frontend:
  url: http://localhost:4200