spring:
  application:
    name: TWITTER_DEV
  datasource:
    url: jdbc:h2:mem:twitter;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true